baseURL = "https://yanzay.github.io/tbot-doc"
languageCode = "en-us"
title = "tbot documentation"
theme = "book"
publishDir = "docs"

[params]
BookMenuBundle = "/menu"

[markup.goldmark.renderer]
unsafe = true